const testReduxState = [
  {
    id: "mainScheme",
    position: { x: 0, y: 0 },
    type: "MainSchemeType",
    draggable:true,
    // className: "light",
    // style: {
    //   width: 360,
    //   height: 30,
    // },
    totalVoltageForAll: "",
    totalPowerOfAllElectricalAppliances:"",
  },
  {
    id: "group1",
    position: { x: 670 * 0, y: 100 },
    type: "TireNodeType",
    draggable:false,
    // className: "light",
    style: {
      width: 360,
      height: 30,
    },
    parentNode: "mainScheme",
  },
  {
    id: "group2",
    position: { x: 670 * 1, y: 100 },
    type: "TireNodeType",
    draggable:false,

    // className: "light",
    style: {
      width: 360,
      height: 30,
    },
    parentNode: "mainScheme",
  },
  {
    id: "1",
    type: "ElectricalPanelsNodeType",
    position: { x: 30, y: 0 },
    parentNode: "group1",
    draggable: false,
    currentCellOption: 0,
    currentTypeOfSwitchingDevice: 0,
    switchingDeviceVV: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      ratedBreakingCurrent: "",
      ratedVoltage: "",
    },
    switchingDeviceVN: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      ratedBreakingCurrent: "",
      ratedVoltage: "",
      numberOfGroundShafts: "",
      locationOfGroundingBlades: "",
      switchDriveLocation: "",
      locationOfTheGroundingBladeDrive: "",
    },
    switchingDeviceR: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      thermalCurrent: "",
      ratedVoltage: "",
    },

    thereIsAFuseCurrent: 0,
    // ===============================================================
    currentTransformatorOption: 1,

    ratedCurrentOfTheMainCircuits: 0, // Номинальный ток главных цепей,А
    opn: {
      type: "",
      name: "",
      manufacturer: "",
      ratedOperatingVoltage: "",
      throughput: "",
      ratedDischargeCurrent: "",
      maximumContinuousPermissibleOperatingVoltage: "",
    },
    microprocessorProtectionDeviceAndAutomation: {
      type: "",
      name: "",
      manufacturer: "",
    },
    electromagneticLocking: {
      type: "",
      name: "",
      manufacturer: "",
    },
    instrumentCurrentTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      transformationRatio: "",
      accuracyClass: "",
      oneSecondThermalCurrent: "",
      typeOfService: "",
    },
    voltageTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      ratedThreePhasePowerOfTheFirstWinding: "",
      accuracyClassOfTheFirstSecondaryWinding: "",
      ratedThreePhasePowerOfTheSecondSecondaryWinding: "",
      accuracyClassOfTheSecondSecondaryWinding: "",
      ratedThreePhasePowerOfAadditionalSecondaryWinding: "",
      accuracyClassOfSecondaryReturnWires: "",
      ratedLineVoltageAtTheTerminalsOfThePrimaryWinding: "",
    },
    currentTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    currentTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    frequencyConvertersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      frequencyMeasurementRange: "",
      quantity: "",
    },
    frequencyConvertersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      frequencyMeasurementRange: "",
      quantity: "",
    },
    voltageTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    voltageTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    powerTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      inputVoltageRange: "",
      outputVoltageRange: "",
      sin: "",
      cos: "",
    },
    powerTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      inputVoltageRange: "",
      outputVoltageRange: "",
      sin: "",
      cos: "",
    },
    circuitBreakers: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrentOfFuseLink: "",
    },
    electricityMeter: {
      type: "",
      name: "",
      manufacturer: "",
      accuracyClass: "",
    },
    transformersForOwnNeeds: {
      type: "",
      name: "",
      manufacturer: "",
      ratedPower: "",
    },
    zeroSequenceCurrentTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      transformationRatio: "",
      oneSecondThermalCurrentOfTheSecondaryWinding: "",
    },
  },
  // ========================================================ITEM #2===============================================================
  {
    // ==========================REACT-FLOW PROPS==========================
    id: "2",
    type: "ElectricalPanelsNodeType",
    position: { x: 0, y: 100 },
    draggable: true,
    // ==========================END OF REACT-FLOW PROPS==========================
    currentCellOption: 2,
    // ==========================КОММУТАЦИОННЫЙ АППАРАТ==========================
    currentTypeOfSwitchingDevice: 1,
    switchingDeviceVV: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      ratedBreakingCurrent: "",
      ratedVoltage: "",
    },
    switchingDeviceVN: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      ratedBreakingCurrent: "",
      ratedVoltage: "",
      numberOfGroundShafts: "",
      locationOfGroundingBlades: "",
      switchDriveLocation: "",
      locationOfTheGroundingBladeDrive: "",
    },
    switchingDeviceR: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrent: "",
      thermalCurrent: "",
      ratedVoltage: "",
    },

    thereIsAFuseCurrent: 0,

    // ==========================КОНЕЦ КОММУТАЦИОННОГО АППАРАТА==========================
    currentTransformatorOption: 2,
    parentNode: "",
    ratedCurrentOfTheMainCircuits: 1,
    opn: {
      type: "",
      name: "",
      manufacturer: "",
      ratedOperatingVoltage: "",
      throughput: "",
      ratedDischargeCurrent: "",
      maximumContinuousPermissibleOperatingVoltage: "",
    },
    microprocessorProtectionDeviceAndAutomation: {
      type: "",
      name: "",
      manufacturer: "",
    },
    electromagneticLocking: {
      type: "",
      name: "",
      manufacturer: "",
    },
    instrumentCurrentTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      transformationRatio: "",
      accuracyClass: "",
      oneSecondThermalCurrent: "",
      typeOfService: "",
    },
    voltageTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      ratedThreePhasePowerOfTheFirstWinding: "",
      accuracyClassOfTheFirstSecondaryWinding: "",
      ratedThreePhasePowerOfTheSecondSecondaryWinding: "",
      accuracyClassOfTheSecondSecondaryWinding: "",
      ratedThreePhasePowerOfAadditionalSecondaryWinding: "",
      accuracyClassOfSecondaryReturnWires: "",
      ratedLineVoltageAtTheTerminalsOfThePrimaryWinding: "",
    },
    currentTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    currentTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    frequencyConvertersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      frequencyMeasurementRange: "",
      quantity: "",
    },
    frequencyConvertersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      frequencyMeasurementRange: "",
      quantity: "",
    },
    voltageTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    voltageTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputVoltageRange: "",
      outputCurrentRange: "",
      quantity: "",
    },
    powerTransducersType1: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      inputVoltageRange: "",
      outputVoltageRange: "",
      sin: "",
      cos: "",
    },
    powerTransducersType2: {
      type: "",
      name: "",
      manufacturer: "",
      numberOfChannels: "",
      inputCurrentRange: "",
      outputCurrentRange: "",
      inputVoltageRange: "",
      outputVoltageRange: "",
      sin: "",
      cos: "",
    },
    circuitBreakers: {
      type: "",
      name: "",
      manufacturer: "",
      ratedCurrentOfFuseLink: "",
    },
    electricityMeter: {
      type: "",
      name: "",
      manufacturer: "",
      accuracyClass: "",
    },
    transformersForOwnNeeds: {
      type: "",
      name: "",
      manufacturer: "",
      ratedPower: "",
    },
    zeroSequenceCurrentTransformers: {
      type: "",
      name: "",
      manufacturer: "",
      transformationRatio: "",
      oneSecondThermalCurrentOfTheSecondaryWinding: "",
    },
  },
  // {
  //   type: "ImageNodeType",
  //   id:'img-1',
  //   src:'',
  //   position: { x: 670 * 0, y: 100 },
  //   style: {
  //     width: 360,
  //     height: 30,
  //   },
  
  // }
];

export default testReduxState;
